server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:~/gamification;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
multiplication:
  exchange: multiplication_exchange
  solved:
    key: multiplication.solved
  queue: gamification_multiplication_queue
  anything:
    routing:
      key: multiplication.*
multiplicationHost: http://localhost:8000/api
eureka:
  client:
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/